# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.require_version '>=2.0.0'

ssh_pub_key_path = File.expand_path(ENV['SSH_PUBLIC_KEY'] || '~/.ssh/id_rsa.pub')
ssh_pub_key = File.exist?(ssh_pub_key_path) ? File.read(ssh_pub_key_path) : ''
ssh_pub_key_script = <<EOF
echo "copying host SSH pubkey into vagrant"
cat >> ~vagrant/.ssh/authorized_keys <<EOT
#{ssh_pub_key}
EOT
EOF

vagrant_profile_path = File.expand_path('~/.vagrant_profile')
vagrant_profile = File.exist?(vagrant_profile_path) ? File.read(vagrant_profile_path) : ''
vagrant_profile_script = <<EOF
echo "copying vagrant_profile into vagrant"
cat > ~vagrant/.vagrant_profile << EOT
#{vagrant_profile}
EOT
EOF

Vagrant.configure(2) do |config|
  config.vm.box = 'hashicorp/precise64'

  config.vm.network :private_network, ip: '10.51.50.91'

  # skip creating a local VM specific ssh key
  config.ssh.insert_key = false
  config.ssh.forward_agent = true

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  config.vm.synced_folder File.expand_path('~/programs'), '/programs'

  config.vm.provider "virtualbox" do |vb|
    # Customize the amount of memory on the VM:
    vb.memory = 2048
    vb.cpus = 2
    vb.auto_nat_dns_proxy = false
    vb.customize ['modifyvm', :id, '--natdnsproxy1', 'off']
    vb.customize ['modifyvm', :id, '--natdnshostresolver1', 'on']
  end

  config.vm.provision :shell, :inline => ssh_pub_key_script
  config.vm.provision :shell, :inline => vagrant_profile_script
  config.vm.provision :shell, :path => './dev.sh'
  config.vm.provision :shell, :path => './docker.sh'
end
