set -o vi
bind '"jk":"\e"'
bind '"kj":"\e"'

LIGHT_GREEN="\[\033[1;32m\]"
YELLOW="\[\033[0;33m\]"
BLUE="\[\033[0;34m\]"
LIGHT_CYAN="\[\033[1;36m\]"
WHITE="\[\033[00m\]"

export EDITOR="vim"
export PS1="$BLUE[$LIGHT_GREEN\u$YELLOW@$LIGHT_GREEN\H$LIGHT_CYAN \w$BLUE]$YELLOW\$(__git_ps1 \"(%s)\")$WHITE\$ "

alias reset_ntp='ntpdate -s time.nist.gov && serivce ntp restart'
