# install tools
install keychain
install docker
install docker-osx
install etcd
install etcdctl
install node
install go
install gpg-agent
install python
install python3
install pngpaste
install readline
install ruby
install wget
install tree
install zsh

# install libraries
install autoconf
install autojump
install automake
install bazaar
install bcrypt
install cmake
install coreutils
install gcc
install gdbm
install gettext
install gnu-getopt
install gnu-sed
install homebrew/dupes/grep
install gnupg2
install gnutls
install libevent
install libffi
install libgcrypt
install libtool
install libyaml
install openssl
install ossp-uuid
install pcre
install pinentry
install pkg-config
install pth
install pwgen
install imagemagick

