# initialize taps
tap caskroom/cask
tap caskroom/versions
tap homebrew/apache
tap homebrew/binary
tap homebrew/boneyard
tap homebrew/dupes
tap homebrew/versions
tap jonmorehouse/tap
update

# install primary applications
install mutt --with-trash-patch
install vim --with-python3
install weechat --with-ruby --with-python --with-perl

# install tools
install bashenv
install docker
install docker-osx
install etcd
install etcdctl
install node
install pass
install brew-cask
install go
install gpg-agent
install hub
install legit
install python
install python3
install pngpaste
install postgresql
install rabbitmq
install readline
install sqlite
install tmux
install reattach-to-user-namespace
install redis
install ruby
install wget
install zeromq
install tree
install urlview
install zsh

# install libraries
install autoconf
install autojump
install automake
install bazaar
install bcrypt
install cmake
install coreutils
install czmq
install gcc
install gdbm
install gettext
install gnu-getopt
install gnu-sed
install gnupg2
install gnutls
install libevent
install libffi
install libgcrypt
install libtool
install libyaml
install openssl
install ossp-uuid
install pcre
install pinentry
install pkg-config
install pth
install pwgen

# install cask files
cask install alfred
cask install iterm2
cask install transmission
cask install carbon-copy-cloner
cask install java
cask install vagrant
cask install dropbox
cask install keyremap4macbook
cask install virtualbox
cask install flowdock
cask install mactex
cask install vlc
cask install google-chrome-canary
cask install pandoc
cask install xquartz
cask install google-hangouts
cask install sizeup
cask install handbrake
cask install skype
